module.exports = {
//   register: require("./admin/register"),
//   login: require("./admin/login"),
//   postRoute: require("./route/createRoute"),
//   updateRoute: require("./route/updateRoute"),
//   fetchRoutes: require("./route/fetchRoutes"),
//   deleteRoute: require("./route/deleteRoute"),
  getCustomers: require("./customer/fetchCustomers"),
  postCustomers: require("./customer/createCustomer"),
//   putBus: require("./bus/updateBus"),
//   deleteBus: require("./bus/deleteBus"),
//   postReservation: require("./reservation/postReservation"),
//   deleteReservation: require("./reservation/deleteReservation"),
//   getPaymentPartners: require("./payment/getPaymentPartners"),
//   azampesaWebhook: require("./payment/callback"),
//   getReservations: require("./reservation/fetchReservaions"),
};
